<?php
//Import PHPMailer classes into the global namespace
//These must be at the top of your script, not inside a function
$env = parse_ini_file(__DIR__ . '/.env');

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

require 'PHPMailer/src/Exception.php';
require 'PHPMailer/src/PHPMailer.php';
require 'PHPMailer/src/SMTP.php';

//Create an instance; passing `true` enables exceptions
$mail = new PHPMailer(true);

try {
    //Server settings
    $mail->SMTPDebug = 0;                      //Enable verbose debug output SMTP::DEBUG_SERVER
    $mail->isSMTP();                                            //Send using SMTP
    $mail->Host       = $env['MAIL_HOST'];                     //Set the SMTP server to send through
    $mail->SMTPAuth   = true;                                   //Enable SMTP authentication
    $mail->Username   = $env['MAIL_USERNAME'];                     //SMTP username
    $mail->Password   = $env['MAIL_PASSWORD'];                               //SMTP password
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;            //Enable implicit TLS encryption
    $mail->Port       = $env['MAIL_PORT'];                                    //TCP port to connect to; use 587/465 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS / PHPMailer::ENCRYPTION_SMTPS`

    //Mail 1: Admin:
    $mail->setFrom($env['MAIL_USERNAME'], "VittaVeda Website");
    $mail->addReplyTo($email, $firstName . " " . $lastName);
    $mail->addAddress("vittavedaent@gmail.com");
    $mail->Subject = "New Consultation Request Received";
    $mail->isHTML(true);
    $mail->Body = '
        <!DOCTYPE html>
        <html>
            <head>
                <meta charset = "UTF-8">
            </head>
            <body style = "margin:0; padding:30; background:#f5f8fa; font-family:Arial,Helvetica,sans-serif;">
                <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                    <td align = "center">
                    <table width = "650" cellpadding = "0" cellspacing = "0" style = "background:#ffffff; border-radius: 12px; overflow:hidden; box-shadow: 0 5px 18px rgba(0,0,0,.08);">
                    <tr>
                    <td style="background:#1f2d42; padding:30px; text-align:center;">
                    <h1 style="margin:0;color:#ffffff;font-size:32px;">VittaVeda</h1>
                    <p style="margin-top:10px;color:#C8A96E;font-size:16px;">New Consultation Request</p>
                    </td>
                </tr>
                <tr>
                    <td style="padding:35px;">
                    <p style="font-size:16px;color:#444;">A new consultation request has been submitted through the website.</p>
                    <table width="100%" cellpadding="10" cellspacing="0" style="border-collapse:collapse;margin-top:25px;">
                    <tr style="background:#f5f8fa;">
                        <td width="35%"><b>Customer Name</b></td>
                        <td>'.$firstName.' '.$lastName.'</td>
                    </tr>
                    <tr>
                        <td><b>Email</b></td>
                        <td>'.$email.'</td>
                    </tr>
                    <tr style="background:#f5f8fa;">
                        <td><b>Phone</b></td>
                        <td>'.$phone.'</td>
                    </tr>
                    <tr>
                        <td><b>Requested Service</b></td>
                        <td>'.$category.'</td>
                    </tr>
                    <tr style="background:#f5f8fa;">
                        <td><b>Submitted On</b></td>
                        <td>'.date("d M Y | h:i A").'</td>
                    </tr>
                    </table>
                    <div style="margin-top:30px; padding:18px; background:#f5f8fa; border-left:5px solid #C8A96E;">
                    <h3 style="margin-top:0;color:#1f2d42;">Customer Message</h3>
                    <p style="margin-bottom:0;color:#444;line-height:1.7;">'.nl2br(htmlspecialchars($message)).'</p>
                    </div>
                    </td>
                </tr>
                <tr>
                    <td style="background:#1f2d42; padding:18px; text-align:center; color:#b2c0d2; font-size:13px;">
                    This is an automated email generated by the
                    <strong style="color:#ffffff;">VittaVeda Website</strong>.
                    </td>
                </tr>
                </table>
                </td>
                </tr>
                </table>
            </body> 
        </html>
    ';
    $mail->send();
    $mail->clearAddresses();
    $mail->clearReplyTos();

    //Mail 2: Customer:
    $mail->setFrom($env['MAIL_USERNAME'], "VittaVeda");
    $mail->addAddress($email, $firstName . " " . $lastName);
    $mail->Subject = "Thank You for Contacting VittaVeda";
    $mail->isHTML(true);
    $mail->addEmbeddedImage(__DIR__ . '/images/Logos/circle-logo.png', 'vittaveda_logo');
    if (!file_exists('images/Logos/main-logo.jpeg')) {
        die("Logo file not found!");
    }
    $mail->Body = '
                    <!DOCTYPE html>
                    <html>
                    <head>
                        <meta charset="UTF-8">
                        <title>Thank You - VittaVeda</title>
                    </head>
                    <body style="margin:0; padding:30px; background:#f5f8fa; font-family:Arial,Helvetica,sans-serif;">
                        <table width="100%" cellpadding="0" cellspacing="0">
                        <tr>
                        <td align="center">
                        <table width="650" cellpadding="0" cellspacing="0" style="background:#ffffff; border-radius:12px; overflow:hidden; box-shadow:0 5px 18px rgba(0,0,0,.08);">
                        <tr>
                        <td style="background:#1f2d42; padding:40px 30px; text-align:center;">
                            <img src="cid:vittaveda_logo" alt="VittaVeda Logo" style=" width:110px; height:110px; border-radius:50%; background:#ffffff; padding:10px; display:block; margin:0 auto  20px auto; box-shadow:0 6px 18px rgba(0,0,0,0.25);">
                            <h1 style="margin:0; color:#ffffff; font-size:36px; font-weight:bold; font-family:Arial,Helvetica,sans-serif; letter-spacing:1px;">

                            VittaVeda

                            </h1>
                            <p style="margin-top:12px; margin-bottom:0; color:#C8A96E; font-size:17px; line-height:28px;">

                            Your Trusted Financial Partner

                            </p>
                        </td>
                        </tr>
                        <tr>
                        <td style="padding:45px;">
                        <h1 style="margin-top:0; color:#1f2d42; font-size:34px; text-align:center;">
                            Thank You!
                        </h1>
                        <div style="width:80px; height:4px; background:#C8A96E; margin:20px auto; border-radius:5px;">
                        </div>
                        <p style="font-size:18px; color:#444; line-height:1.8;">
                        Dear
                        <b>'.$firstName.' '.$lastName.'</b>,
                        </p>
                        <p style="font-size:17px; line-height:1.8; color:#555;">
                        Thank you for choosing
                        <b style="color:#1f2d42;">VittaVeda</b>.
                        We have successfully received your consultation request.
                        </p>
                        <p style="font-size:17px; line-height:1.8; color:#555;">
                        One of our financial experts will carefully review your request and contact you shortly.
                        </p>
                    </body>
                    </html>';
    $mail->send();
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}