CREATE DATABASE vittaveda_db;
USE vittaveda_db;
CREATE TABLE TBL_CONSULTATION_REQUESTS (
REQUEST_ID INT AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(255),
PHONE VARCHAR(15) NOT NULL,
SERVICE_CATEGORY VARCHAR(100) NOT NULL,
MESSAGE TEXT,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM TBL_CONSULTATION_REQUESTS;
DESCRIBE TBL_CONSULTATION_REQUESTS;
TRUNCATE TABLE TBL_CONSULTATION_REQUESTS;